# Generated by Django 5.2.16 on 2026-07-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Marka Adı")),
                (
                    "vertical",
                    models.CharField(
                        help_text="Örn: Ai-Juris, Ai-Health",
                        max_length=100,
                        verbose_name="Dikey/Sektör",
                    ),
                ),
                ("target_audience", models.TextField(verbose_name="Hedef Kitle")),
                (
                    "brand_voice",
                    models.CharField(
                        help_text="Örn: Profesyonel, Samimi",
                        max_length=100,
                        verbose_name="Marka Tonu/Sesi",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Marka Açıklaması"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marka Profili",
                "verbose_name_plural": "Marka Profilleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Kampanya Adı")),
                ("objective", models.TextField(verbose_name="Kampanya Amacı/Hedefi")),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Bütçe",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Taslak"),
                            ("ACTIVE", "Aktif"),
                            ("COMPLETED", "Tamamlandı"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="marketing_api.brandprofile",
                        verbose_name="Marka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kampanya",
                "verbose_name_plural": "Kampanyalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketingContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("LINKEDIN", "LinkedIn"),
                            ("X", "X (Twitter)"),
                            ("INSTAGRAM", "Instagram"),
                            ("FACEBOOK", "Facebook"),
                            ("GOOGLE_ADS", "Google Ads"),
                            ("META_ADS", "Meta Ads"),
                            ("BLOG", "Blog Post"),
                            ("EMAIL", "E-posta Kampanyası"),
                        ],
                        max_length=50,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Sadece Metin"),
                            ("IMAGE", "Metin & Görsel"),
                            ("VIDEO", "Metin & Video"),
                        ],
                        default="TEXT",
                        max_length=20,
                        verbose_name="İçerik Tipi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ajan Bekleniyor"),
                            ("GENERATING", "Üretiliyor"),
                            ("READY", "İncelemeye Hazır"),
                            ("FAILED", "Başarısız Oldu"),
                            ("PUBLISHED", "Yayınlandı"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "generated_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Üretilen Metin"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Medya Bağlantısı (Görsel/Video)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="marketing_api.campaign",
                        verbose_name="Kampanya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pazarlama İçeriği",
                "verbose_name_plural": "Pazarlama İçerikleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
