# Generated by Django 5.2.16 on 2026-07-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcontent',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='Ek Bilgi'),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='length',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Uzunluk'),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='tone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ton'),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Konu'),
        ),
    ]
