# Generated by Django 5.2.16 on 2026-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_api', '0002_marketingcontent_extra_info_marketingcontent_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcontent',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planlanan Tarih/Saat'),
        ),
    ]
