# Generated by Django 5.2.16 on 2026-07-25 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_api', '0003_marketingcontent_scheduled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-posta Bildirimleri')),
                ('weekly_report', models.BooleanField(default=True, verbose_name='Haftalık Performans Raporu')),
                ('push_notifications', models.BooleanField(default=False, verbose_name='Tarayıcı (Push) Bildirimleri')),
                ('ai_tips', models.BooleanField(default=True, verbose_name='AI Önerileri ve İpuçları')),
                ('content_ready', models.BooleanField(default=True, verbose_name='İçerik Hazır Olduğunda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim Tercihi',
                'verbose_name_plural': 'Bildirim Tercihleri',
            },
        ),
    ]
