# Generated by Django 5.2.16 on 2026-07-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_api', '0005_brandprofile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='accent_color',
            field=models.CharField(default='#4a47a3', max_length=20, verbose_name='Vurgu Rengi'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='color_saturation',
            field=models.CharField(default='orta', max_length=20, verbose_name='Renk Yoğunluğu'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Koyu Tema'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='font_family',
            field=models.CharField(default='Inter', max_length=50, verbose_name='Yazı Tipi'),
        ),
    ]
