# Generated by Django 5.2.16 on 2026-07-27 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing_api", "0006_notificationpreference_accent_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="TOTP Secret Anahtarı",
                    ),
                ),
                (
                    "is_totp_enabled",
                    models.BooleanField(default=False, verbose_name="2FA Aktif mi?"),
                ),
                (
                    "backup_codes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Yedek Kodlar"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
            },
        ),
    ]
