# Generated by Django 5.2.16 on 2026-07-27 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing_api", "0007_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brandprofile",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Silinme Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="brandprofile",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Silinme Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="marketingcontent",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Silinme Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="marketingcontent",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Eylem")),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="Detaylar"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarih"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "İşlem Logu",
                "verbose_name_plural": "İşlem Logları",
                "ordering": ["-created_at"],
            },
        ),
    ]
