# Generated by Django 5.2.16 on 2026-07-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketing_api",
            "0008_brandprofile_deleted_at_brandprofile_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingcontent",
            name="language",
            field=models.CharField(
                choices=[("tr", "Türkçe"), ("en", "İngilizce")],
                default="tr",
                max_length=10,
                verbose_name="Dil",
            ),
        ),
    ]
