# Generated by Django 5.2.16 on 2026-08-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_api', '0007_brandprofile_deleted_at_brandprofile_is_deleted_and_more'),
        ('marketing_api', '0009_marketingcontent_language'),
    ]

    operations = [
    ]
